initial commit of quadratic voting code
Cryptonomic/Smart-Contracts pull request #105
Opened 2023-06-28 15:38 UTC by dwariyar

Closes #104.

2023-06-28 16:33 UTC, vishakh requested changes

2023-06-28 16:33 UTC, vishakh commented on Etherium/Voting/_Quadratic_Voting.sol
Using either the [Remix IDE](https://remix.ethereum.org/#lang=en&optimize=false&runs=200&evmVersion=null) or [ethers.js](https://docs.ethers.org/v5/), could you please create unit tests to establish that the contract behaves as expected?

2023-06-28 16:33 UTC, vishakh commented on Etherium/Voting/_Quadratic_Voting.sol
> +    function sqrt(uint y) internal pure returns (uint z) {
Try to use a standard library such as [SafeMath](https://docs.openzeppelin.com/contracts/2.x/api/math) to ensure that the math is robust. This is preferable to rolling your own utility functions.

2023-06-28 16:33 UTC, vishakh commented on Etherium/Voting/_Quadratic_Voting.sol
> +    function stringToBytes32(string memory source) public pure returns (bytes32 result) {
Try to use a library function here.

2023-06-28 16:35 UTC, vishakh commented on Etherium/Voting/_Quadratic_Voting.sol
"Ethereum" is misspelled in the path.

2023-08-24 18:58 UTC, vishakh requested changes

2023-08-24 18:58 UTC, vishakh commented on Ethereum/Voting/_Quadratic_Voting.sol
> +    //return proposals[proposalNames[j]].voteCount;
Could we either implement this function or remove it?

2023-08-24 18:58 UTC, vishakh commented on Ethereum/Voting/_Quadratic_Voting.sol
> +
Could you make the spacing between functions consistent?

2023-08-25 02:12 UTC, dwariyar commented on Ethereum/Voting/_Quadratic_Voting.sol
> +    //return proposals[proposalNames[j]].voteCount;
removed it

2023-08-25 02:12 UTC, dwariyar commented on Ethereum/Voting/_Quadratic_Voting.sol
> +
changed spacing

2023-08-25 12:51 UTC, vishakh approved these changes

2023-08-25 12:51 UTC, merged